<?php

define('REQUEST_SUCCESS', 10000);
define('REQUEST_FAILED', 10001);

define('RESPONSE_SUCCESS', 0);

// 权限等级
define('AUTHORIZATION_LEVEL_ALL_ALLOWED', 3);
define('AUTHORIZATION_LEVEL_ON_USER', 2);
define('AUTHORIZATION_LEVEL_ALL_DENIED', 1);
